name = "tcb-bank-ui"
compatibility_date = "2026-04-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "tcb-ledger-v2"
database_id = "7c86e16f-67fd-4730-a74e-2536ed824b77"
